---
title: "Analysis of World Population"
description: |
  This website would give you an idea about the current world population and different indices based upon population.
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(distill)
library(rvest)
library(tidyverse)
library(ggthemes)
library(plotly)
library(scales)
# library()
# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

# Learn more about publishing to GitHub Pages at:
# https://rstudio.github.io/distill/publish_website.html#github-pages

pop_den_grow <- read.csv('Population, Growth and Density Data.csv')
loan <- read.csv('Loan Progression.csv')
economics_life <- merge(x = pop_den_grow, y = loan, by = "Country")
economics_life <- economics_life |>
  drop_na() |>
  mutate(GrowthRate = (GrowthRate - 1))


```

*`Population vs Growth Rate`*

The relation between population of a country is depicted in the graph below. Key finding from this graph is "**Growth rate is inversely proportional to income category."**

```{r}

# Population and Density
plot <- economics_life |>
  drop_na() |>
  select(Country, pop2022, Density, Continent) |>
  ggplot(aes(Density, pop2022, color = Continent)) +
  geom_point()+
    scale_x_log10(labels = comma)+
    scale_y_log10(labels = comma)

ggplotly(plot)

```

```{r}
plot <- economics_life |>
  drop_na() |>
  ggplot(aes(Density, Area, color = Continent)) +
  geom_point()+
    scale_x_log10(labels = comma)

ggplotly(plot)

```

```{r}
plot <- economics_life |>
    
    select(GrowthRate, income.group, Region, Continent) |>
    ggplot(aes(y = GrowthRate, x = income.group, color = Continent)) +
    geom_point()+
    scale_y_continuous(labels = percent)

ggplotly(plot)
```

```{r}
plot <- economics_life |>
    group_by(Lending.category) |>
    summarise(count = n())

```